name: PartyDeluxe
main: whirss.partydeluxe.Main
version: 1.8
author: Whirss, InstanceLabs
softdepend: [PlaceholderAPI, Vault]
commands:
   partydeluxe:
      aliases: [pd, pg]
      description: Command for players
      usage: /partydeluxe [action]
   partydeluxeadmin:
      aliases: [pda, pga]
      description: Command for admins
      usage: /partydeluxeadmin [action]
