name: MinecraftParty
main: whirss.minecraftparty.Main
version: 1.6
author: Whirss, InstanceLabs
depend: [Vault]
commands:
   minecraftparty:
      aliases: [mp, mcparty, mcp]
      description: Main command
      usage: /minecraftparty [action]
